### ISSUE TITLE
Feature: Please allow running this plugin as a post-build action

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#10]
It'd be most awesome if one could run this plugin (sending messages to salt-api) as a post-build action, depending (configurable) on the main build step status (was if successfull of not)

**Comment by mchugh19** [comment]
I've seen this handled as a later build action in the same project or, possibly better, as a post build action to "build other projects" where that other project contains the salt call. This allows you to track the pipeline and determine which specific step had an error. If the saltapi call were to fail-out or hang in post build, that would complicate the project since the build was marked successful. 

If you are looking to conditionally run the salt call depending on the success/failure of previous builds, then you might want to look at the post build "build other project" action as you can specify kicking the next build on success or failure. 

Would that work for your use-case, or is a post build step still valuable?

**Comment by zerthimon** [comment]
@mchugh19 Thanks for the insigt, your solution looks interesting and I'll use it as a workaround. 
In my use case I'm building docker image in main build step, which I'd like to deploy with salt (i have an SLS which creates containers) as post-build action, depending on the main build status. So, I was looking for a simple way to do that with existing tools.

**Comment by mchugh19** [comment]
I think you will find that jenkins better handles your use case by chaining together multiple projects into a pipeline. In your case it sounds like you would be well served by having a docker build project that on success kicks off a deployment project. This allows you to create pipeline with individually monitorable or replaceable components and enables you to add additional steps such as dev -> staging -> production or better yet, dev -> test -> staging -> test -> production.

See jenkins plugins https://wiki.jenkins-ci.org/display/JENKINS/Delivery+Pipeline+Plugin or https://wiki.jenkins-ci.org/display/JENKINS/Build+Pipeline+Plugin

I'll close out this issue as it sounds like your situation is being handled, but feel free to reporen as necessary.

**Comment by zerthimon** [comment]
Thanks a lot @mchugh19 .
