### ISSUE TITLE
Salt API returns TimeoutError on Jenkins Pipeline

### ISSUE THREAD

**Issue by RTechSoft** [jenkinsci/saltstack-plugin#60]
Hi Everyone,

Has anyone here encountered these errors before?

`[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deployment)
[Pipeline] withCredentials
[Pipeline] {
[Pipeline] sh
[staging-server] Running shell script
+ curl -sS 10.10.214.233:8181/run -H Accept: application/x-yaml -d client=local -d tgt=minion.id -d fun=cmd.run -d arg=/bin/sh -e /home/user/scripts/deployment.sh -d username=**** -d password=**** -d eauth=pam
Unrecoverable error in the server.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 180, in trap
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 99, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 410, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 234, in __init__
    self.run()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 349, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError
+ echo 0
0
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS`

The script successfully executed on the minion server but failed to return the build log.

**Jenkins version:** 2.32.2
**SaltStack plugin version:** 2.0.1

Any thoughts?

**Comment by mchugh19** [comment]
In this example, you don't seem to be using the Jenkins Saltstack plugin at all. 😺 

The /run endpoint allows you to kick off a message on the salt event bus. This works well if the job does its thing and returns. However, if the job is long living, you will not necessarily get a reply as you might hit a timeout (as seems to be the case here). To account for this, the Jenkins plugin has an option to send the message to the saltapi, get back the job ID that was just sent, then poll for the results of the jid.

Since you are using pipeline, the equivalent command using the Jenkins Saltstack plugin would be as follows (where the credentialsId should map to the id in your instance):
```
salt authtype: 'pam', clientInterface: local(arguments: '"/bin/sh -e /home/user/scripts/deployment.sh"', blockbuild: true, function: 'cmd.run', jobPollTime: 16, target: 'minion.id', targetType: 'glob'), credentialsId: 'f1016814-ebce-4d70-9af3-6bf61e56ebb4', servername: 'http://10.10.214.233:8181'
```

You can mess around and generate the pipeline output by clicking the "Pipeline Syntax" link at the bottom of a pipeline job. This will open up viewer where you can select the salt plugin, and then populate the options in the gui. Once everything is in place, you can hit the "Generate Pipeline Script" button at the bottom to generate the pipeline output.

**Comment by RTechSoft** [comment]
Thanks @mchugh19. It's a great suggestion indeed. I already used that pipeline script before, before I got into the curl option solution.

A problem with the Salt Plugin using pipeline script, we always got a "FAILED" build on Jenkins even it was a successfully built on the salt minion. I wander around the net to find a fix solution on this but failed to got a concrete answer. Your thoughts about this?

**Comment by mchugh19** [comment]
If you send over the json return that is being marked as a bad build, I can correct the validation to have it pass successfully.

**Comment by mchugh19** [comment]
@RTechSoft Could you please send over an example json return that is failing the build?

**Comment by mchugh19** [comment]
Version 2.1.0 was just released and should have tighter validation of salt responses. Please test and let me know if this resolves your issue.

**Comment by mchugh19** [comment]
I'm going to close this out as a newer version of the plugin has tighter rules on detecting failures, which hopefully solves your issues. 

I suggest you use the Jenkins plugin rather than just shell out to curl as the plugin works across platforms and without needing curl, supports Jenkins credentials for password handling, more easily supports salt's functionality (such as jid handling which was the issue here, easy /hook support, salt-run/orchestrate execution, and timeout of unresponsive minions), and detects resulting salt failures.

If you have any problems, please feel free to open this back up.
