### ISSUE TITLE
Feature: Allow disabling SSL cert check when connecting to salt-api

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#64]
Having a self-signed cert on salt-api causes java ssl error:
```
"Error": "javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
It'd be nice to have an option to talk to salt-apis without having to add CA certs to java cert store.

**Comment by mchugh19** [comment]
Hmmm. I don't feel comfortable bypassing the keystore. If misused this could have bad implications since salt holds so much control. I think it is important to ensure certs are trusted and that you are connected to the host you intended; leaving only the option here to explicitly configure the keystore.

I'm going to mark this as wontfix and closing it out. But if you have additional thoughts, feel free to reopen.

**Comment by thenozzl3** [comment]
Would like to +1 this . It would make this plugin way more useful where you are driving deployments with salt and jenkins (esp. when using this as a part of promotion pipeline).
