### ISSUE TITLE
Suggestion: Use the flyweight executor for salt jobs?

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/saltstack-plugin#75]
It's possible to use the [input](https://jenkins.io/doc/pipeline/steps/pipeline-input-step/) step without consuming an executor. Maybe this could be a good idea for this plugin as well? It should still be possible to block builds if required by using the [Lockable Resources](https://jenkins.io/doc/pipeline/steps/lockable-resources/) plugin. Some hints on how to implement this might be available in the [source for the input plugin](https://github.com/jenkinsci/pipeline-input-step-plugin).

Thoughts?

**Comment by mchugh19** [comment]
The flyweight executors are run on the master and aren't intended to do any heavy lifting. Because of that, they don't consume an executor slot. Those are all pretty good features for a plugin that does a simple http query.

However, the lightweight-ness of these features come at a little bit of a cost. In the current form, by executing on a Jenkins agent, you can query the saltapi from the context of that agent. So if the agent lives within a DMZ and the salt connection needs to be made with a DNS name that is only resolvable from that agent, this now works within the node workspace. Additionally, by running on the agent, you can suspend and resume the Jenkins master, without affecting a long running job.

Here's an example of starting a cmd.run of 'sleep 120; ls -ls'. While the saltapi plugin was running, I restart the Jenkins master, the salt command still completed successfully and returned the output to Jenkins. 
```
Started by user anonymous
[Pipeline] node
Running on agent1 in /tmp/workspace/dpipeline
Resuming build at Sat Apr 08 07:26:00 IST 2017 after Jenkins restart
Ready to run at Sat Apr 08 07:26:07 IST 2017
[Pipeline] salt
Running jid: 20170408062607856244
Waiting for 2 minions
0 minions are done
Will check status every 6 seconds...
[Pipeline] echo
[{"minion1":{"return":"total 20\ndrwx-- ...  .ssh"}}]
```

So given the resume-ability and context of running in a node, I'd say that's a worthy tradeoff.

**Comment by rbjorklin** [comment]
Sounds fair to me, cool that you provided use-cases :)
