### ISSUE TITLE
Configuration are lost after upgrade

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/saltstack-plugin#90]
Hi,

I have upgraded the plugin from 1.7.1 to 3.0.0 and all SaltAPI configuration are lost.
Please advise.

Thanks!
Ido

**Comment by idokaplan** [comment]
Any update?

**Comment by mchugh19** [comment]
Yep. Was traveling a bunch recently. While on the plane I started on this in the [compat](https://github.com/jenkinsci/saltstack-plugin/tree/compat) branch

**Comment by idokaplan** [comment]
Thank you for your update.
1. Is it possible to prevent this issue?
2. is it possible to restore the jobs after they have deleted?

**Comment by mchugh19** [comment]
1. The compat branch will hopefully correct this issue
2. Jobs aren't actually deleted. The issue is that the format of the salt plugin was adjusted, and after the plugin update, Jenkins is no longer able to read the old format. The saltstack instructions are still in jobs/jobname/config.xml, it's just not being read in by Jenkins. This will hopefully be corrected soon.

**Comment by idokaplan** [comment]
Ok, When do you think that you will release a fix?

**Comment by mchugh19** [comment]
This is now working, but with a necessary manual step. 

Please try the beta release from:
https://github.com/jenkinsci/saltstack-plugin/releases/tag/v3.1.0-beta2

As mentioned on the release notes:
Due to human error, there is a manual step necessary to fully import pre 2.0 build configs. If the Jenkins migrate old data page at administrativeMonitor/OldData/manage shows the error `ConversionException: Cannot construct com.waytta.clientinterface.BasicClient` then delete the `<clientInterface>` line from the config. This can be done with:
`sed -i'.bak' '/<clientInterface>.*<\/clientInterface>/d' jenkinshome/jobs/jobname/config.xml`

At this point reloading configs should restore the job data.

The rest of the old job config import, combined with improved support for long running pipeline jobs should be in the 3.1 release.

**Comment by mchugh19** [comment]
This was corrected in release 3.1 (same as the mentioned beta above and still requires the manual step). Should be available on the mirrors in the next 24 hours.

**Comment by idokaplan** [comment]
Great! it's working!
